### ISSUE TITLE
Add application, models for 107

### ISSUE THREAD

**Issue by travishen** [COAStatistics/alss-dev#12]

**Comment by MatsuiLin101** [comment]
### Survey變更為Survey19
新增`second`及`non_second`，紀錄表1.4戶內是否有二代青農

### 新增FarmLocation代表107調查基本資料新增的可耕作地或畜牧用地所在地區 
`survey`一對一關連到Survey19  
`city`代表縣市  
`town`代表鄉鎮市區  
`code`關連到CityTownCode  

### 新增CityTownCode記錄各縣市鄉鎮市區的代號  
`city`代表縣市  
`town`代表鄉鎮市區  
`code`代表縣市及鄉鎮市區的代號  

### 修改CropMarketing  
移除`total_yield`及`unit_price`  
新增`year_sales`代表全年銷售額  
新增`name`代表作物名稱  

### 修改LivestockMarketing  
移除`total_yield`及`unit_price`  
新增`year_sales`代表全年銷售額  
新增`name`代表畜禽(產品)名稱  

### 移除Facility  
`CropMarketing`已有`has_facility`  

### 修改Population  
移除`other_farm_work`，107調查沒有此選項  

### 修改LongTermLack  
新增`avg_lack_day`代表107調查新增的平均每月短缺日數(日)  

### 修改ShortTermLack  
新增`avg_lack_day`代表107調查新增的平均每月短缺日數(日)  
新增`name`代表107調查新增的作物名稱  

### 移除OtherFarmWork  
107調查沒有此問項

**Comment by travishen** [comment]
Survey變更為Survey19是因為哪裡有衝突嗎？

**Comment by MatsuiLin101** [comment]
修改Product
新增`min_hour`代表作物最小工時，可為空值
新增`max_hour`代表作物最大工時，可為空值
新增`display`將子類作物在前端隱藏不顯示

**Comment by travishen** [comment]
### 修改Survey
移除`is_update`，今年無主力農家

### 修改Product
新增`management_type`，關聯至ManagementType

**Comment by travishen** [comment]
### 修改FarmerWorkDay
移除`min_day`、`max_day`，用於計算工時

### 修改Product
新增`min_hour`、`max_hour`，用於計算工時
