### ISSUE TITLE
3.2.1 檢務條件修改

### ISSUE THREAD

**Issue by MatsuiLin101** [COAStatistics/alss-dev#75]
若勾選「107年有人力但不穩定或未來有缺工可能」及「107年有人力但若增加人力可縮短工作日數或擴充產能」，目前會顯示【問項3.2.2及3.2.3】應為空白。

檢務條件修正為，不檢查問項【問項3.2.2及3.2.3】是否空白。

**Comment by travishen** [comment]
@MatsuiLin101 
看不太懂，是不檢查，還是顯示`不檢查問項【問項 3.2.2 及 3.2.3】是否空白`？
