### ISSUE TITLE
農業外僱人力提醒出現undefined

### ISSUE THREAD

**Issue by wups101** [COAStatistics/alss-dev#80]
3.1 僱用情形
這內容為什麼出現 undefined(0)?

合理工作時數下限：枇杷(2325) + 瓊麻(0) + undefined(0) = 2325小時
合理工作時數上限：枇杷(2658) + 瓊麻(0)) + undefined(0) = 2658小時

![image](https://user-images.githubusercontent.com/35325179/56487689-a5602580-650e-11e9-84fc-49e439790fcd.png)

資料內容：
![image](https://user-images.githubusercontent.com/35325179/56487798-fff98180-650e-11e9-8f0c-3e68cd889fd7.png)

![image](https://user-images.githubusercontent.com/35325179/56487809-0982e980-650f-11e9-9476-a37ff2c4e689.png)

**Comment by travishen** [comment]
@wups101 
沒有畜禽？
