### ISSUE TITLE
3.1.2 長僱員工新增儲存後日數和月份出現錯誤

### ISSUE THREAD

**Issue by wups101** [COAStatistics/alss-dev#96]
1. 新增資料，當月份/日數空白，接著儲存
![image](https://user-images.githubusercontent.com/35325179/56600862-4c86af00-662c-11e9-9f80-30c75e9c9f3e.png)

2. 要修正時會出錯
![image](https://user-images.githubusercontent.com/35325179/56600786-252fe200-662c-11e9-907e-2c703c894884.png)

**Comment by travishen** [comment]
@wups101 
這錯誤我沒辦法重現

**Comment by wups101** [comment]
@travishen 我現在測就沒有出錯了!
