### ISSUE TITLE
轉移106年資料 `update_datetime` 變成 loaddata 的當下時間

### ISSUE THREAD

**Issue by travishen** [COAStatistics/alss-dev#97]
轉移 106 年資料 `logs.ReviewLog.update_datetime` 變成 loaddata 的當下時間，106年的Model應該都有同樣的問題

方向是只處理 ReviewLog ，surveys18 的 Model 先不處理

![image](https://user-images.githubusercontent.com/28494579/56603397-45fb3600-6632-11e9-9ee1-1c01352d959c.png)

應該是 `auto_now=True` 導致：
```
    update_datetime = DateTimeField(
        auto_now=True,
        auto_now_add=False,
        null=True,
        blank=True,
        verbose_name=_("Updated"),
    )
```

可能的解法，但可能要寫腳本去執行：
https://docs.djangoproject.com/en/2.2/ref/models/instances/#specifying-which-fields-to-save

**Comment by MatsuiLin101** [comment]
loaddata 並不會造成 update_datetime 的時間被改寫，`auto_now=True`在loaddata時不會起作用，只有在`instance.save()`時觸發。

此問題是因為2019/04/23 15:52:21時，我在server上去改寫106的ReviewLog的content_type造成的。

解決方法是編輯匯出的106年ReviewLog，將content_type改成正確的app_id，再重新執行loaddata

![image](https://user-images.githubusercontent.com/30253055/56627542-dbb9b400-6678-11e9-8a26-521a6997e9de.png)

![image](https://user-images.githubusercontent.com/30253055/56627773-cb560900-6679-11e9-895c-e2f61696e503.png)
